spring.application.name=rba-it

server.servlet.context-path=/api

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

cors.allowed-origins=http://localhost:5173

spring.datasource.url=jdbc:h2:file:./data/rba-it;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.consumer.group-id=rba-it
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

kafka.topic.card-status-change=card-status-change